
//User
export const REGISTER_FAMILY = "REGISTER_FAMILY";
export const REGISTER_FAMILY_DONE = "REGISTER_FAMILY_DONE";
export const REGISTER_PERSON = "REGISTER_PERSON";
export const REGISTER_PERSON_DONE = "REGISTER_PERSON_DONE";

export const LOGIN_FAMILY = "LOGIN_FAMILY";
export const LOGIN_FAMILY_DONE = "LOGIN_FAMILY_DONE";

export const SET_IS_FAM_AUTH = "SET_IS_FAM_AUTH";
export const SET_IS_PARENT_AUTH = "SET_IS_PARENT_AUTH";
export const SET_IS_CHILD_AUTH = "SET_IS_CHILD_AUTH";

export const SET_FAMILY_DATA = "SET_FAMILY_DATA";
export const SET_FAMILY_DATA_DONE = "SET_FAMILY_DATA_DONE";


//Schedule
